name: Push Apps Script

# Configures the workflow to run on pull request events, feel free to change this according to your needs
on:
  pull_request:

env:
  # Apps Script project ID
  APPS_SCRIPT_PROJECT_ID: my-apps-script-project
  # Directory within your GitHub repository containing the script code
  SCRIPT_DIR: ./script-code

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      # Is necessary to create access tokens
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate to GCP using your custom project and service account
      - uses: google-github-actions/auth@v2
        id: google-auth
        with:
          project_id: my-gcp-project
          workload_identity_provider: projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: my-svc-account@my-gcp-project.iam.gserviceaccount.com
          # User to be impersonated via domain-wide-delegation, take user for which the Apps Script projects have been created
          access_token_subject: my-user@example.com
          token_format: access_token
          # These access token scopes are mandatory when you want to update the script content
          # see https://developers.google.com/apps-script/api/reference/rest/v1/projects/updateContent 
          access_token_scopes: "https://www.googleapis.com/auth/script.projects"

      - name: Push script
        uses: shiftavenue/gas-action@v0
        with:
          # Use push command
          command: push
          project-id: ${{ env.APPS_SCRIPT_PROJECT_ID }}
          access-token: ${{ steps.google-auth.outputs.access_token }}
          script-dir: ${{ env.SCRIPT_DIR }}
